# Generated by Django 4.0.2 on 2022-05-05 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_client_id_alter_deliverorder_id_alter_drink_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='address',
            new_name='officeNumber',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='birthday',
            new_name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='client',
            name='birthday',
        ),
        migrations.AddField(
            model_name='client',
            name='dateOfBirth',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
