# Generated by Django 4.0.2 on 2022-05-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_address_client_officenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='officeNumber',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='dateOfBirth',
            new_name='birthday',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='dateOfBirth',
            new_name='birthday',
        ),
    ]
